version: '3.9'

services:
  database:
    container_name: database
    image: postgres:latest
    env_file:
      - ./backend/.env
    ports:
      - 5050:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_is_ready -U theus -d talks"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    # volumes:
    #   - contactportfolio:/var/lib/postgresql/data:rw

  # server:
  #   container_name: server
  #   build: ./backend
  #   ports:
  #     - 3001:3001
  #   env_file:
  #     - ./backend/.env
  #   depends_on:
  #     - database
  #   volumes:
  #     - .:/usr/app

# volumes:
#   contactportfolio:
#     external: true